name:                zzc 
version:             0.1.0
github:              "ruzen42/zzc"
license:             BSD-3-Clause
author:              "Ruzen42"
maintainer:          "ruzen@tuta.io"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Compiler for ZZlang
category:            System

description:         Please see the README on GitHub at <https://github.com/ruzen42/zzc#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - bytestring
  - mtl
  - text
  - vector
  - base
  - megaparsec
  - unordered-containers
  - binary

executables:
  zzc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zzc 
    - text
    - mtl
    - vector

tests:
  zzlang-compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zzc
