name:                zzlang-compiler
version:             0.1.1.0
github:              "ruzen42/zzlang-compiler"
license:             BSD-3-Clause
author:              "Jaroslav Mihajlenko"
maintainer:          "malledeferlive@gmail.com"
copyright:           "GPLv3"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Compiler for ZZlang
category:            System

description:         Please see the README on GitHub at <https://github.com/ruzen42/zzlang-compiler#readme>

build-tools:
- alex
- happy

dependencies:
- base >= 4.7 && < 5
- parsec
- array
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - mtl
  - aeson
  - bytestring
  - text
  - base

executables:
  zzc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zzlang-compiler
    - optparse-applicative

tests:
  zzlang-compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zzlang-compiler
